# Generated by Django 5.2.17 on 2026-09-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='موضوع / نوع همکاری')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده؟')),
            ],
            options={
                'verbose_name': 'پیام ارتباطی',
                'verbose_name_plural': 'پیام\u200cهای ارتباطی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='امین اسماعیل زاده', max_length=120, verbose_name='نام و نام خانوادگی')),
                ('role_title', models.CharField(default='توسعه\u200cدهنده خلاق فرانت\u200cاند و طراح اینتراکشن', max_length=200, verbose_name='عنوان شغلی')),
                ('bio', models.TextField(blank=True, verbose_name='بیوگرافی')),
                ('email', models.EmailField(default='amin.esmaeilzadehh@gmail.com', max_length=254, verbose_name='ایمیل مستقیم')),
                ('phone', models.CharField(default='09011312210', max_length=30, verbose_name='شماره تماس')),
                ('location', models.CharField(default='گرگان، ایران / ریموت بین\u200cالمللی', max_length=120, verbose_name='موقعیت')),
                ('telegram_url', models.URLField(default='https://t.me/AminOmade', verbose_name='آدرس تلگرام')),
                ('github_url', models.URLField(default='https://github.com/Amin-Ezz', verbose_name='آدرس گیت\u200cهاب')),
                ('linkedin_url', models.URLField(default='https://www.linkedin.com/in/amin-esmaeil-zadeh-a99503431', verbose_name='آدرس لینکدین')),
                ('resume_url', models.CharField(default='/Amin_Esmaeilzadeh_Resume.pdf', max_length=255, verbose_name='لینک فایل رزومه')),
            ],
            options={
                'verbose_name': 'اطلاعات پروفایل',
                'verbose_name_plural': 'اطلاعات پروفایل',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='شناسه یکتا (Slug)')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان پروژه')),
                ('subtitle', models.CharField(blank=True, max_length=250, verbose_name='زیرعنوان')),
                ('tagline', models.CharField(blank=True, max_length=255, verbose_name='شعار پروژه')),
                ('category', models.CharField(max_length=150, verbose_name='دسته\u200cبندی')),
                ('year', models.CharField(default='۲۰۲۶', max_length=20, verbose_name='سال انجام')),
                ('role', models.CharField(max_length=200, verbose_name='نقش')),
                ('technologies', models.JSONField(blank=True, default=list, verbose_name='فناوری\u200cها')),
                ('live_url', models.URLField(blank=True, verbose_name='لینک نسخه زنده')),
                ('github_url', models.URLField(blank=True, verbose_name='لینک مخزن گیت\u200cهاب')),
                ('hero_image', models.CharField(max_length=255, verbose_name='تصویر شاخص')),
                ('detail_images', models.JSONField(blank=True, default=list, verbose_name='تصاویر بخش\u200cهای جزئیات')),
                ('accent_color', models.CharField(default='#EAEAEA', max_length=30, verbose_name='رنگ تم')),
                ('overview', models.TextField(verbose_name='توضیحات کلی')),
                ('problem', models.TextField(blank=True, verbose_name='چالش و مسئله')),
                ('solution', models.TextField(blank=True, verbose_name='راهکار فنی')),
                ('process', models.JSONField(blank=True, default=list, verbose_name='مراحل انجام کار')),
                ('metrics', models.JSONField(blank=True, default=list, verbose_name='دستاوردهای کلیدی')),
                ('next_slug', models.CharField(blank=True, max_length=100, verbose_name='اسلاگ پروژه بعدی')),
                ('next_title', models.CharField(blank=True, max_length=100, verbose_name='عنوان پروژه بعدی')),
                ('prev_slug', models.CharField(blank=True, max_length=100, verbose_name='اسلاگ پروژه قبلی')),
                ('prev_title', models.CharField(blank=True, max_length=100, verbose_name='عنوان پروژه قبلی')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مهارت')),
                ('category', models.CharField(choices=[('frontend', 'فرانت\u200cاند'), ('motion', 'انیمیشن و تعامل ۳بعدی'), ('backend', 'بک\u200cاند و معماری'), ('tools', 'ابزارها و بهینه\u200cسازی')], default='frontend', max_length=50, verbose_name='دسته\u200cبندی')),
                ('proficiency', models.IntegerField(default=90, verbose_name='درصد تسلط (۰ تا ۱۰۰)')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'مهارت\u200cها',
                'ordering': ['order', 'name'],
            },
        ),
    ]
